### PR TITLE
Fixes some v2 yaml parsing 🐹

### LINKED ISSUE #291: build: path not supported
```yaml
version: '2'
services:
  app:
    build: app
    image: app
```

won't parse correctly due to [this line](https://github.com/docker/libcompose/blob/master/config/merge_v2.go#L189) even though it is correct v2 [syntax](https://docs.docker.com/compose/compose-file/#build)

### PR DESCRIPTION
**Pull request by vdemeester**
This PR does two things:

#### Store config version in project 🐮 

This is needed for `networks` and `volumes` support as we are gonna need to know the version of the config file to act based on it.

#### Some `yaml` refactoring/magic and `config` updates 🐹

Doing several things: 
- Split into smaller files (with test) to make it easier to read.
- Add a `Build` type that handle some Build magic
- Add an `External` type that handle some external magic (networks, volumes)
- Add `Networks`/`Network` type that handle some Networks magic
- Refactor the `Ulimit` types to be simpler and not user reflection

Also adds a `merge_fixtures_test.go` and `testdata` folder with some existing compose file to make sure it parses it well (should serve as quick regression tests in the future too).

/cc @joshwget (master of the yaml :joy: :stuck_out_tongue_closed_eyes:)

Fixes  #291
Needed for #277 and #288 implementations

🐸 🐸

### CODE REVIEW

File: yaml/build.go [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+				continue
+			}
+		}
+	default:
+		return fmt.Errorf("Failed to unmarshal Build: %#v", value)
+	}
+	return nil
+}
+
+func handleBuildArgs(value interface{}) (map[string]string, error) {
```
Comment (joshwget) [inline yaml/build.go]: Maybe we shouldn't make these two functions specific to build arguments. We'll probably have to do something similar for logging arguments, so maybe we can move these to a `utils.go`?

File: yaml/network.go [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+				network.Aliases = []string{}
+				for _, alias := range aliases {
+					network.Aliases = append(network.Aliases, alias.(string))
+				}
+			case "ipv4_address":
+				network.IPv4Address = mapValue.(string)
+			case "ipv6_address":
+				network.IPv6Address = mapValue.(string)
+			default:
+				// Ignorer unknown keys ?
```
Comment (joshwget) [inline yaml/network.go]: Validation (once it's done for v2) should complain about unknown keys :smile:

**Comment by joshwget** [comment]
Returning the config version is definitely a good idea. Awesome work with all of the new types. Hopefully that wasn't too tedious!

Just one comment, but LGTM other than that.

File: yaml/build.go (hunk 1 above)
Comment (vdemeester) [inline yaml/build.go]: Hum right now `logging` key works fine, but I'll keep that in mind because yeah, that's a pretty generic way of handling a map :angel:
